version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx..."
      - yum clean all
      - rm -f /var/run/yum.pid || true
      - yum makecache
      - yum update -y || echo "Yum update failed but continuing..."
      - yum install -y nginx


  build:
    commands:
      - echo "Starting Nginx..."
      - cp index.html /var/www/html/index.html
  
  post_build:
    commands:
    
      - echo "Build completed successfully."

artifacts:
  files:
    - /var/www/html/index.html
