version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx..."
      - yum clean all
      - rm -f /var/run/yum.pid || true
      - yum makecache
      - yum install -y nginx

  build:
    commands:
      - echo "Copying index.html..."
      - cp index.html /usr/share/nginx/html/

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - index.html

