version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx..."
      - sudo yum update -y
      - sudo yum install -y nginx 

  build:
    commands:
      - echo "Starting Nginx..."
      - cp index.html /var/www/html/index.html
  
  post_build:
    commands:
    
      - echo "Build completed successfully."

artifacts:
  files:
    - /var/www/html/index.html
