version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx..."
      - yum clean all
      - rm -f /var/run/yum.pid || true
      - yum makecache
      - yum install -y nginx

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Copying website files to /var/www/html..."
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/
      - echo "Listing /var/www/html contents..."
      - ls -la /var/www/html

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - /var/www/html/index.html
    - appspec.yml
    - 'scripts/**/*'


